import { Inter } from "next/font/google";
import "./globals.css";


import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { AppProvider } from "@/context/AppContext";
import { ThemeProvider } from "@/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: {
		default: "Events App",
		template: "%s | Events",
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
	return (
		<html lang={locale}>
			<body>
				<AppProvider>
					<ThemeProvider>
						<div className="container">
							<Navbar />
							{children}
							<Footer/>
						</div>
					</ThemeProvider>
				</AppProvider>
			</body>
		</html>
	);
}
